build:
  dependencies:
    override:
      - echo 'Override -'
  environment:
    php:
      version: 7.1
filter:
  excluded_paths:
    - build/*
    - config/*
    - tests/*
checks:
  php:
    code_rating: true