build:
  dependencies:
    override:
      - true
  environment:
    php:
      version: 7.1
filter:
  excluded_paths:
    - build/*
    - config/*
    - tests/*
    - src/Pyz/*
checks:
  php:
    code_rating: true