build:
  dependencies:
    override:
      - la -ls src
  environment:
    php:
      version: 7.1
filter:
  excluded_paths:
    - build/*
    - tests/*
    - vendor/*
    - config/Shared/*
    - src/Generated/*
    - src/Pyz/*
checks:
  php:
    code_rating: true