build:
  dependencies:
    override:
      - composer config repositories.spryker-private composer https://code.spryker.com/repo/private
      - composer install
      - echo "Finished Project Level Build"
  environment:
    php:
      version: 7.1
filter:
  excluded_paths:
    - build/*
    - config/*
    - tests/*
checks:
  php:
    code_rating: true