build:
  dependencies:
    before:
      - cat composer.json
      - sed -i -e 's/"spryker"\:/""\:/g' composer.json
      - cat composer.json
  environment:
    php:
      version: 7.1
filter:
  excluded_paths:
    - build/*
    - config/*
    - tests/*
checks:
  php:
    code_rating: true