build:
  dependencies:
    before:
      - composer config repositories.spryker composer https://code.spryker.com/repo/private
  environment:
    php:
      version: 7.1
filter:
  excluded_paths:
    - build/*
    - tests/*
    - vendor/*
    - config/Shared/*
    - src/Generated/*
    - src/Pyz/*
checks:
  php:
    code_rating: true