language: php

env:
  global:
    - APPLICATION_ENV=devtest
    - APPLICATION_STORE=DE
    - APPLICATION_=DE

matrix:
  fast_finish: true
  include:
     - php: "7.0"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - postgresql
  - redis

sudo: required

addons:
  postgresql: 9.4
  apt:
    packages:
      - graphviz
  hosts:
    - zed.de.spryker.test
    - www.de.spryker.test

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - chmod +x move-module.sh
  - ./move-module.sh
  - echo "Cloning demoshop..."
  - git clone https://github.com/spryker/demoshop.git demoshop
  - cd demoshop/
  - chmod -R a+x config/Shared/ci/travis/
  - composer self-update && composer --version
  - composer install --no-interaction
  - config/Shared/ci/travis/install_elasticsearch.sh

before_script:
  - nvm install 6
  - mkdir -p shared/data/common/jenkins/jobs
  - mkdir -p data/DE/cache/Yves/twig
  - mkdir -p data/DE/cache/Zed/twig
  - mkdir -p data/DE/logs
  - chmod -R 777 data/
  - mv config/Zed/propel.ci.yml config/Zed/propel.yml
  - cat config/Shared/ci/travis/postgresql_ci.config >> config/Shared/ci/travis/config_ci.php
  - cp config/Shared/ci/travis/config_ci.php config/Shared/config_default-devtest_DE.php
  - cp config/Shared/ci/travis/params_test_env.sh deploy/setup/params_test_env.sh
  - cd ..
  - chmod a+x ./module/travis.sh

script:
  - ./module/travis.sh

notifications:
  email: false
