language: php

env:
  global:
    - APPLICATION_ENV=devtest
    - APPLICATION_STORE=DE
    - APPLICATION_=DE

matrix:
  fast_finish: true
  include:
     - php: "7.0"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

sudo: required

addons:
  postgresql: 9.4
  apt:
    packages:
      - graphviz
  hosts:
    - zed.de.spryker.test
    - www.de.spryker.test

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - chmod +x move-module.sh
  - ./move-module.sh
  - echo "Cloning demoshop..."
  - git clone https://github.com/spryker/demoshop.git current
  - cd current/
  - composer self-update && composer --version
  - composer install --no-interaction

before_script:
  - nvm install 6
  - mkdir -p data/DE/cache/Yves/twig
  - mkdir -p data/DE/cache/Zed/twig
  - mkdir -p data/DE/logs
  - chmod -R 777 data/
  - cd ..
  - chmod a+x ./module/travis.sh

script:
  - ./module/travis.sh

notifications:
  email: false
