<?php  //[STAMP] daab0b585cc3562b56080a93e48ff86c
namespace SprykerTest\Zed\Econda\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use SprykerTest\Shared\Testify\Helper\Environment;
use SprykerTest\Shared\Testify\Helper\ConfigHelper;
use SprykerTest\Shared\Propel\Helper\TransactionHelper;

trait EcondaBusinessTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param string $key
     * @param array|bool|float|int|string $value
     *
     * @return void
     * @see \SprykerTest\Shared\Testify\Helper\ConfigHelper::setConfig()
     */
    public function setConfig($key, $value) {
        return $this->getScenario()->runStep(new \Codeception\Step\Action('setConfig', func_get_args()));
    }

 
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param string $key
     *
     * @return void
     * @see \SprykerTest\Shared\Testify\Helper\ConfigHelper::removeConfig()
     */
    public function removeConfig($key) {
        return $this->getScenario()->runStep(new \Codeception\Step\Action('removeConfig', func_get_args()));
    }
}
